language: php
php:
  - '5.6'
  - '7.0'

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server


before_script:
  - pecl install mongodb
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit

service:
  - mongodb

notifications:
  webhooks: https://hook.bearychat.com/=bw8Px/travis/f259b29d3c7b88076f2da0cfd18d1490