language: php
php:
  - '5.6'
  - '7.0'
  - hhvm

before_script:
  - cp .env.travis .env
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

service:
  - mongodb